import turtle
miguel = turtle.Turtle()
BG=turtle.Screen()
BG.bgcolor("light blue")

#M
miguel.pencolor("purple")
miguel.shape("triangle")
miguel.goto(-200,0)
miguel.pensize(14)
miguel.left(90)
miguel.forward(120)
miguel.right(140)
miguel.forward(90)
miguel.left(108)
miguel.forward(90)
miguel.right(140)
miguel.forward(130)
#A
miguel.pencolor("pink")
miguel.left(155)
miguel.forward(135)
miguel.right(140)
miguel.forward(67)
miguel.right(110)
miguel.forward(45)
miguel.right(180)
miguel.forward(45)
miguel.right(70)
miguel.forward(67)
#U
miguel.pencolor("red")
miguel.shape("turtle")
miguel.left(159)
miguel.forward(120)
miguel.right(180)
miguel.forward(90)
miguel.left(40)
miguel.forward(35)
miguel.left(50)
miguel.forward(30)
miguel.left(50)
miguel.forward(30)
miguel.left(40)
miguel.forward(95)
#M
miguel.pencolor("yellow")
miguel.shape("circle")
miguel.right(179)
miguel.forward(120)
miguel.left(180)
miguel.forward(120)
miguel.right(140)
miguel.forward(70)
miguel.left(110)
miguel.forward(70)
miguel.right(140)
miguel.forward(135)

#Cometa
import turtle
cometa=turtle.Turtle()
colors=['red', 'purple']
for i in range (10):
    for i in range (2):
        cometa.color(colors[i%8])
        cometa.goto(120,-185)
        cometa.forward(100)
        cometa.right(60)
        cometa.forward(100)
        cometa.right(120)
    cometa.right(36) 